version: '3.8'

services:
  web:
    build: .
    container_name: cafe_orders_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: cafe_orders_db
    environment:
      POSTGRES_DB: cafe_orders_db
      POSTGRES_USER: cafe_orders_user
      POSTGRES_PASSWORD: cafe_orders_pass
    ports:
      - "5432:5432"
